b2.0.0 first steps of refactoring

diff --git a/action/gorpupgrade b/action/gorpupgrade
--- a/action/gorpupgrade
+++ b/action/gorpupgrade
@@ -11,12 +11,20 @@
 
 
 
-# PERMISSIONS GUARD
+#### GUARDS ################
 
-if [[ "$EUID" != 0 ]]; then
-    echo "gorpupgrade: Insufficient privilege. Exiting."
-    exit
+### ROOT GUARD
+
+if [[ "$EUID" == 0 ]]; then
+    echo "Please do not run as root or with 'sudo'. Gorp will ask for sudo rights if it needs it. Exit (10)."
+    exit 10
 fi
+
+
+
+#### SCRIPT PARAMETERS ################
+
+HOMEDIR=$(getHomedir)
 
 
 
@@ -24,28 +32,28 @@ fi
 
 
 
-# TEMP DIRECTORY
+### TEMP DIRECTORY
 
-rm -rf /minecraft/tmp
-mkdir /minecraft/tmp
+rm -rf $HOMEDIR/tmp/
+mkdir $HOMEDIR/tmp/
 
 
 
-# GIT CLONE LATEST C.U.M. FILES
+### GIT CLONE LATEST GORP FILES
 
 echo "gorpupgrade: Downloading newest scripts..."
 
-git clone --quiet https://github.com/LanceNickel/Gorp /minecraft/tmp/updatefiles
+git clone --quiet https://github.com/LanceNickel/Gorp $HOMEDIR/tmp/updatefiles
 
 
 
-# RUN UPDATE WORKER
+### RUN UPDATE WORKER
 
-chmod +x /minecraft/tmp/updatefiles/upgrade.sh
-/minecraft/tmp/updatefiles/upgrade.sh
+chmod +x $HOMEDIR/tmp/updatefiles/upgrade.sh
+$HOMEDIR/tmp/updatefiles/upgrade.sh pleasedontdothis
 
 
 
-# CLEAN UP
+### CLEAN UP
 
-rm -rf /minecraft/tmp
+rm -rf $HOMEDIR/tmp/
diff --git a/action/mcarchiveworld b/action/mcarchiveworld
--- a/action/mcarchiveworld
+++ b/action/mcarchiveworld
@@ -12,19 +12,22 @@
 
 
 
-# PERMISSIONS GUARD
+#### GUARDS ################
 
-if [[ "$EUID" != 0 ]]; then
-    echo "mcarchiveworld: Insufficient privilege. Exiting."
-    exit
+### KEY GUARD
+
+if [[ "$1" != "pleasedontdothis" ]]; then
+    echo "mcarchiveworld: Not intended to be run directly. Exit (13)."
+    exit 13
 fi
 
 
 
-# SCRIPT VARIABLES
+#### SCRIPT PARAMETERS ################
 
-SERVER=$1
-WORLD_TO_ARCHIVE=$2
+HOMEDIR=$(getHomedir)
+SERVER=$2
+WORLD_TO_ARCHIVE=$3
 
 
 
@@ -32,53 +35,53 @@ WORLD_TO_ARCHIVE=$2
 
 
 
-# PARAM GUARD
+# PARAM RT-GUARD
 
-if [ "$SERVER" = "" ]; then
-    echo "mcarchiveworld: Server name missing. Expected command format: 'gorp archive-world [server-name] <world-name>'"
-    exit
+if [[ "$SERVER" = "" ]]; then
+    echo "mcarchiveworld: Server name missing. Expected command format: 'gorp archive-world [server-name] <world-name>'. Exit (14)."
+    exit 14
 fi
 
 
 
-# SERVER DIRECTORY GUARD
+# SERVER DIRECTORY RT-GUARD
 
-if [ -d "/minecraft/servers/$SERVER" ]; then
+if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
     sleep 0.05
 else
-    echo "mcarchiveworld: Server doesn't exist. Exiting."
-    exit
+    echo "mcarchiveworld: Server doesn't exist. Exit (20)."
+    exit 20
 fi
 
 
 
-# NO WORLDS GUARD
+# NO WORLDS RT-GUARD
 
-if [[ $(ls /minecraft/servers/$SERVER/ | grep 'world') = "" ]]; then
-    echo -e "mcarchiveworld: No worlds exist on this server instance.\nRun 'gorp create-world $SERVER [name]' to create a new world. Exiting."
-    exit
+if [[ $(ls $HOMEDIR/servers/$SERVER/ | grep 'world') = "" ]]; then
+    echo -e "mcarchiveworld: No worlds exist on this server instance.\nRun 'gorp create-world $SERVER [name]' to create a new world. Exit (20)."
+    exit 20
 fi
 
 
 
-# SCREEN GUARD
+# SCREEN RT-GUARD
 
 if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
-        echo "mcarchiveworld: Server '$SERVER' is running. Stop the server and then archive the world. Exiting."
-        exit
+        echo "mcarchiveworld: Server cannot be running. Exit (32)."
+        exit 32
 fi
 
 
 
-# WORLD DIRECTORY GUARD (when world name passed as param)
+# WORLD DIRECTORY RT-GUARD (when world name passed as param)
 
 if [ "$WORLD_TO_ARCHIVE" != "" ]; then
 
-    if [ -d "/minecraft/servers/$SERVER/world-$WORLD_TO_ARCHIVE" ]; then
+    if [ -d "$HOMEDIR/servers/$SERVER/world-$WORLD_TO_ARCHIVE" ]; then
         sleep 0.005
     else
-        echo "mcarchiveworld: A world with name '$WORLD_TO_ARCHIVE' doesn't exist. Exiting."
-        exit
+        echo "mcarchiveworld: A world with name '$WORLD_TO_ARCHIVE' doesn't exist. Exit (42)."
+        exit 42
     fi
 
 fi
@@ -87,4 +90,4 @@ fi
 
 # RUN THE WORLD ARCHIVE WORKER
 
-/usr/local/bin/gorputils/worker/archiveworld.sh $SERVER $WORLD_TO_ARCHIVE
+/usr/local/bin/gorpmc/worker/archiveworld.sh pleasedontdothis $SERVER $WORLD_TO_ARCHIVE
diff --git a/action/mccreateworld b/action/mccreateworld
--- a/action/mccreateworld
+++ b/action/mccreateworld
@@ -12,19 +12,22 @@
 
 
 
-# PERMISSIONS GUARD
+#### GUARDS ################
 
-if [[ "$EUID" != 0 ]]; then
-    echo "mccreateworld: Insufficient privilege. Exiting."
-    exit
+### KEY GUARD
+
+if [[ "$1" != "pleasedontdothis" ]]; then
+    echo "mccreateworld: Not intended to be run directly. Exit (13)."
+    exit 13
 fi
 
 
 
-# SCRIPT VARIABLES
+#### SCRIPT PARAMETERS ################
 
-SERVER=$1
-NEW_WORLD=$2
+HOMEDIR=$(getHomedir)
+SERVER=$2
+NEW_WORLD=$3
 
 
 
@@ -32,48 +35,48 @@ NEW_WORLD=$2
 
 
 
-# PARAM GUARD
+# PARAM RT-GUARD
 
 if [ "$SERVER" = "" ]; then
-    echo "mccreateworld: Server name missing. Expected command format: 'gorp create-world [server-name] <world-name>'"
-    exit
+    echo "mccreateworld: Server name missing. Expected command format: 'gorp create-world [server-name] <world-name>'. Exit (14)."
+    exit 14
 fi
 
 
 
-# SERVER DIRECTORY GUARD
+# SERVER DIRECTORY RT-GUARD
 
-if [ -d "/minecraft/servers/$SERVER" ]; then
+if [ -d "$HOMEDIR/servers/$SERVER" ]; then
     sleep 0.05
 else
-    echo "mccreateworld: Server doesn't exist. Exiting."
-    exit
+    echo "mccreateworld: Server doesn't exist. Exit (20)."
+    exit 20
 fi
 
 
 
-# WORLD DIRECTORY GUARD (when world name passed as param)
+# WORLD DIRECTORY RT-GUARD (when world name passed as param)
 
 if [ "$NEW_WORLD" != "" ]; then
 
-    if [ -d "/minecraft/servers/$SERVER/world-$NEW_WORLD" ]; then
-        echo "mccreateworld: A world with name '$NEW_WORLD' already exists. Exiting."
-        exit
+    if [ -d "$HOMEDIR/servers/$SERVER/world-$NEW_WORLD" ]; then
+        echo "mccreateworld: A world with name '$NEW_WORLD' already exists. Exit (21)."
+        exit 21
     fi
 
 fi
 
 
 
-# SCREEN GUARD
+# SCREEN RT-GUARD
 
 if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
-        echo "mccreateworld: Server '$SERVER' is running. Stop the server and then create a new world. Exiting."
-        exit
+        echo "mccreateworld: Server cannot be running. Exit (32)."
+        exit 32
 fi
 
 
 
 # RUN THE WORLD CREATOR WORKER
 
-/usr/local/bin/gorputils/worker/createworld.sh $SERVER $NEW_WORLD
+/usr/local/bin/mc/worker/createworld.sh pleasedontdothis $SERVER $NEW_WORLD
diff --git a/action/mcdeleteserver b/action/mcdeleteserver
--- a/action/mcdeleteserver
+++ b/action/mcdeleteserver
@@ -11,18 +11,21 @@
 
 
 
-# PERMISSIONS GUARD
+#### GUARDS ################
 
-if [[ "$EUID" != 0 ]]; then
-    echo "mcdelete: Insufficient privilege. Exiting."
-    exit
+### KEY GUARD
+
+if [[ "$1" != "pleasedontdothis" ]]; then
+    echo "mcdeleteserver: Not intended to be run directly. Exit (13)."
+    exit 13
 fi
 
 
 
-# SCRIPT VARIABLES
+#### SCRIPT PARAMETERS ################
 
-SERVER=$1
+HOMEDIR=$(getHomedir)
+SERVER=$2
 
 
 
@@ -30,44 +33,44 @@ SERVER=$1
 
 
 
-# PARAM GUARD
+# PARAM RT-GUARD
 
 if [ "$SERVER" = "" ]; then
-    echo "mcdelete: Please specify a server. Exiting"
-    exit
+    echo "mcdeleteserver: Please specify a server. Exit (14)."
+    exit 14
 fi
 
 
 
-# NO SERVERS GUARD
+# NO SERVERS RT-GUARD
 
-if [[ $(ls /minecraft/servers/) = "" ]]; then
-    echo -e "mcdeleteserver: No server instances exist..\nRun 'gorp create-server [name]' to create a new server."
-    exit
+if [[ $(ls $HOMEDIR/servers/) = "" ]]; then
+    echo -e "mcdeleteserver: No server instances exist..\nRun 'gorp create-server [name]' to create a new server. Exit (20)."
+    exit 20
 fi
 
 
 
-# SERVER DIRECTORY GUARD
+# SERVER DIRECTORY RT-GUARD
 
-if [ -d "/minecraft/servers/$SERVER" ]; then
-    cd /minecraft/servers/$SERVER
+if [ -d "$HOMEDIR/servers/$SERVER" ]; then
+    cd $HOMEDIR/servers/$SERVER
 else
-    echo "mcdelete: Specified server doesn't exist. Exiting."
-    exit
+    echo "mcdeleteserver: Specified server doesn't exist. Exit (20)."
+    exit 20
 fi
 
 
 
-# SCREEN GUARD
+# SCREEN RT-GUARD
 
 if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
-        echo "mcdelete: Server '$SERVER' is still running. Please stop the server first. Exiting."
-        exit
+        echo "mcdeleteserver: Server cannot be running. Exit (32)."
+        exit 32
 fi
 
 
 
 # RUN DELETE WORKER
 
-/usr/local/bin/gorputils/worker/deleteserver.sh $SERVER
+/usr/local/bin/gorpmc/worker/deleteserver.sh pleasedontdothis $SERVER
