action refactor wave 1

diff --git a/action/mcarchiveworld b/action/mcarchiveworld
--- a/action/mcarchiveworld
+++ b/action/mcarchiveworld
@@ -38,7 +38,7 @@ WORLD_TO_ARCHIVE=$3
 # PARAM RT-GUARD
 
 if [[ "$SERVER" = "" ]]; then
-    echo "mcarchiveworld: Server name missing. Expected command format: 'gorp archive-world [server-name] <world-name>'. Exit (14)."
+    echo "mcarchiveworld: Bad input. Please provide a server name. Expected input: 'gorp archive-world [server-name] <world-name>. Exit (14)."
     exit 14
 fi
 
@@ -49,8 +49,8 @@ fi
 if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
     sleep 0.05
 else
-    echo "mcarchiveworld: Server doesn't exist. Exit (20)."
-    exit 20
+    echo "mcarchiveworld: Server not found. Exit (30)."
+    exit 30
 fi
 
 
@@ -58,8 +58,8 @@ fi
 # NO WORLDS RT-GUARD
 
 if [[ $(ls $HOMEDIR/servers/$SERVER/ | grep 'world') = "" ]]; then
-    echo -e "mcarchiveworld: No worlds exist on this server instance.\nRun 'gorp create-world $SERVER [name]' to create a new world. Exit (20)."
-    exit 20
+    echo -e "mcarchiveworld: No worlds exist on this server. Exit (42)."
+    exit 42
 fi
 
 
@@ -67,8 +67,8 @@ fi
 # SCREEN RT-GUARD
 
 if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
-        echo "mcarchiveworld: Server cannot be running. Exit (32)."
-        exit 32
+        echo "mcarchiveworld: Server cannot be running. Exit (34)."
+        exit 34
 fi
 
 
@@ -80,7 +80,7 @@ if [ "$WORLD_TO_ARCHIVE" != "" ]; then
     if [ -d "$HOMEDIR/servers/$SERVER/world-$WORLD_TO_ARCHIVE" ]; then
         sleep 0.005
     else
-        echo "mcarchiveworld: A world with name '$WORLD_TO_ARCHIVE' doesn't exist. Exit (42)."
+        echo "mcarchiveworld: World not found. Exit (40)."
         exit 42
     fi
 
diff --git a/action/mcbackupworld b/action/mcbackupworld
--- a/action/mcbackupworld
+++ b/action/mcbackupworld
@@ -24,8 +24,8 @@ fi
 
 #### SCRIPT PARAMETERS ################
 
-HOMEDIR=$(getHomedir)
 SERVER=$2
+HOMEDIR=$(getHomedir)
 
 
 
@@ -36,8 +36,8 @@ SERVER=$2
 # PARAM RT-GUARD
 
 if [ "$SERVER" = "" ]; then
-    echo "mcbackupworld: Please specify a server. Exiting."
-    exit
+    echo "mcbackupworld: Bad input. Expected: gorp backup-world [server-name]. Exit (14)."
+    exit 14
 fi
 
 
@@ -48,8 +48,8 @@ if [ -d "$HOMEDIR/servers/$SERVER" ]; then
     # we can continue
     sleep 0.005
 else
-    echo "mcbackupworld: Specified server doesn't exist. Exiting."
-    exit
+    echo "mcbackupworld: Server not found. Exit (30)."
+    exit 30
 fi
 
 
@@ -57,8 +57,8 @@ fi
 # NO WORLDS RT-GUARD
 
 if [[ $(ls $HOMEDIR/servers/$SERVER/ | grep 'world') = "" ]]; then
-    echo -e "mcbackupworld: No worlds exist on this server instance.\nRun 'gorp create-world $SERVER [name]' to create a new world. Exiting."
-    exit
+    echo -e "mcbackupworld: No worlds exist on this server. Exit (42)."
+    exit 42
 fi
 
 
diff --git a/action/mccreateworld b/action/mccreateworld
--- a/action/mccreateworld
+++ b/action/mccreateworld
@@ -25,9 +25,9 @@ fi
 
 #### SCRIPT PARAMETERS ################
 
-HOMEDIR=$(getHomedir)
 SERVER=$2
 NEW_WORLD=$3
+HOMEDIR=$(getHomedir)
 
 
 
@@ -49,8 +49,8 @@ fi
 if [ -d "$HOMEDIR/servers/$SERVER" ]; then
     sleep 0.05
 else
-    echo "mccreateworld: Server doesn't exist. Exit (20)."
-    exit 20
+    echo "mccreateworld: Server not found. Exit (30)."
+    exit 30
 fi
 
 
@@ -60,8 +60,8 @@ fi
 if [ "$NEW_WORLD" != "" ]; then
 
     if [ -d "$HOMEDIR/servers/$SERVER/world-$NEW_WORLD" ]; then
-        echo "mccreateworld: A world with name '$NEW_WORLD' already exists. Exit (21)."
-        exit 21
+        echo "mccreateworld: World already exists. Exit (41)."
+        exit 41
     fi
 
 fi
@@ -71,8 +71,8 @@ fi
 # SCREEN RT-GUARD
 
 if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
-        echo "mccreateworld: Server cannot be running. Exit (32)."
-        exit 32
+        echo "mccreateworld: Server cannot be running. Exit (34)."
+        exit 34
 fi
 
 
diff --git a/action/mcdeleteserver b/action/mcdeleteserver
--- a/action/mcdeleteserver
+++ b/action/mcdeleteserver
@@ -24,8 +24,8 @@ fi
 
 #### SCRIPT PARAMETERS ################
 
-HOMEDIR=$(getHomedir)
 SERVER=$2
+HOMEDIR=$(getHomedir)
 
 
 
@@ -36,17 +36,8 @@ SERVER=$2
 # PARAM RT-GUARD
 
 if [ "$SERVER" = "" ]; then
-    echo "mcdeleteserver: Please specify a server. Exit (14)."
+    echo "mcdeleteserver: Bad input. Expected: gorp delete-server [server-name]. Exit (14)."
     exit 14
-fi
-
-
-
-# NO SERVERS RT-GUARD
-
-if [[ $(ls $HOMEDIR/servers/) = "" ]]; then
-    echo -e "mcdeleteserver: No server instances exist..\nRun 'gorp create-server [name]' to create a new server. Exit (20)."
-    exit 20
 fi
 
 
@@ -56,8 +47,8 @@ fi
 if [ -d "$HOMEDIR/servers/$SERVER" ]; then
     cd $HOMEDIR/servers/$SERVER
 else
-    echo "mcdeleteserver: Specified server doesn't exist. Exit (20)."
-    exit 20
+    echo "mcdeleteserver: Server not found. Exit (30)."
+    exit 30
 fi
 
 
@@ -65,8 +56,8 @@ fi
 # SCREEN RT-GUARD
 
 if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
-        echo "mcdeleteserver: Server cannot be running. Exit (32)."
-        exit 32
+        echo "mcdeleteserver: Server cannot be running. Exit (34)."
+        exit 34
 fi
 
 
diff --git a/action/mcdeleteworld b/action/mcdeleteworld
--- a/action/mcdeleteworld
+++ b/action/mcdeleteworld
@@ -12,19 +12,22 @@
 
 
 
-# PERMISSIONS GUARD
+#### GUARDS ################
 
-if [[ "$EUID" != 0 ]]; then
-    echo "mcdeleteworld: Insufficient privilege. Exiting."
-    exit
+### KEY GUARD
+
+if [[ "$1" != "pleasedontdothis" ]]; then
+    echo "mcdeleteworld: Not intended to be run directly. Exit (13)."
+    exit 13
 fi
 
 
 
-# SCRIPT VARIABLES
+#### SCRIPT PARAMETERS ################
 
-SERVER=$1
-WORLD_TO_DELETE=$2
+SERVER=$2
+WORLD_TO_DELETE=$3
+HOMEDIR=$(getHomedir)
 
 
 
@@ -32,53 +35,53 @@ WORLD_TO_DELETE=$2
 
 
 
-# PARAM GUARD
+# PARAM RT-GUARD
 
-if [ "$SERVER" = "" ]; then
-    echo "mcdeleteworld: Server name missing. Expected command format: 'gorp delete-world [server-name] <world-name>'"
-    exit
+if [[ "$SERVER" = "" ]]; then
+    echo "mcdeleteworld: Bad input. Expected: gorp delete-world [server-name] <world-name>. Exit (14)."
+    exit 14
 fi
 
 
 
-# SERVER DIRECTORY GUARD
+# SERVER DIRECTORY RT-GUARD
 
-if [ -d "$HOMEDIR/servers/$SERVER" ]; then
+if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
     sleep 0.05
 else
-    echo "mcdeleteworld: Server doesn't exist. Exiting."
-    exit
+    echo "mcdeleteworld: Server not found. Exit (30)."
+    exit 30
 fi
 
 
 
-# NO WORLDS GUARD
+# NO WORLDS RT-GUARD
 
 if [[ $(ls $HOMEDIR/servers/$SERVER/ | grep 'world') = "" ]]; then
-    echo -e "mcdeleteworld: No worlds exist on this server instance.\nRun 'gorp create-world $SERVER [name]' to create a new world. Exiting."
-    exit
+    echo -e "mcdeleteworld: No worlds exist on this server. Exit (42)."
+    exit 42
 fi
 
 
 
-# SCREEN GUARD
+# SCREEN RT-GUARD
 
 if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
-        echo "mcdeleteworld: Server '$SERVER' is running. Stop the server and then delete the world. Exiting."
-        exit
+        echo "mcdeleteworld: Server cannot be running. Exit (34)."
+        exit 34
 fi
 
 
 
-# WORLD DIRECTORY GUARD (when world name passed as param)
+# WORLD DIRECTORY RT-GUARD (when world name passed as param)
 
-if [ "$WORLD_TO_DELETE" != "" ]; then
+if [[ "$WORLD_TO_DELETE" != "" ]]; then
 
     if [ -d "$HOMEDIR/servers/$SERVER/world-$WORLD_TO_DELETE" ]; then
         sleep 0.005
     else
-        echo "mcdeleteworld: A world with name '$WORLD_TO_DELETE' doesn't exist. Exiting."
-        exit
+        echo "mcdeleteworld: World not found. Exit (40)."
+        exit 40
     fi
 
 fi
@@ -87,4 +90,4 @@ fi
 
 # RUN THE WORLD DELETE WORKER
 
-/usr/local/bin/gorpmc/worker/deleteworld.sh $SERVER $WORLD_TO_DELETE
+/usr/local/bin/gorpmc/worker/deleteworld.sh pleasedontdothis $SERVER $WORLD_TO_DELETE
diff --git a/action/mcresetworld b/action/mcresetworld
--- a/action/mcresetworld
+++ b/action/mcresetworld
@@ -12,20 +12,22 @@
 
 
 
-# PERMISSIONS GUARD
+#### GUARDS ################
 
-if [[ "$EUID" != 0 ]]; then
-    echo "mcresetworld: Insufficient privilege. Exiting."
-    exit
+### KEY GUARD
+
+if [[ "$1" != "pleasedontdothis" ]]; then
+    echo "mcresetworld: Not intended to be run directly. Exit (13)."
+    exit 13
 fi
 
 
 
-# SCRIPT VARIABLES
+#### SCRIPT PARAMETERS ################
 
-SERVER=$1
-WORLD_TO_DELETE=$2
-
+SERVER=$2
+WORLD_TO_DELETE=$3
+HOMEDIR=$(getHomedir)
 
 
 ####
@@ -34,20 +36,20 @@ WORLD_TO_DELETE=$2
 
 # PARAM GUARD
 
-if [ "$SERVER" = "" ]; then
-    echo "mcresetworld: Server name missing. Expected command format: 'gorp reset-world [server-name]'"
-    exit
+if [[ "$SERVER" = "" ]]; then
+    echo "mcresetworld: Bad input. Expected: gorp reset-world [server-name] <world-name>. Exit (14)."
+    exit 14
 fi
 
 
 
 # SERVER DIRECTORY GUARD
 
-if [ -d "$HOMEDIR/servers/$SERVER" ]; then
+if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
     sleep 0.05
 else
-    echo "mcresetworld: Server doesn't exist. Exiting."
-    exit
+    echo "mcresetworld: Server not found. Exit (30)."
+    exit 30
 fi
 
 
@@ -55,12 +57,12 @@ fi
 # NO WORLDS GUARD
 
 if [[ $(ls $HOMEDIR/servers/$SERVER/ | grep 'world') = "" ]]; then
-    echo -e "mcresetworld: No worlds exist on this server instance.\nRun 'gorp create-world $SERVER [name]' to create a new world. Exiting."
-    exit
+    echo -e "mcresetworld: No worlds exist on this server. Exit (42)."
+    exit 42
 fi
 
 
 
 # RUN THE WORLD DELETE WORKER
 
-/usr/local/bin/gorpmc/worker/resetworld.sh $SERVER
+/usr/local/bin/gorpmc/worker/resetworld.sh pleasedontdothis $SERVER
diff --git a/action/mcrestoreworld b/action/mcrestoreworld
--- a/action/mcrestoreworld
+++ b/action/mcrestoreworld
@@ -11,20 +11,21 @@
 
 
 
-# PERMISSIONS GUARD
+#### GUARDS ################
 
-if [[ "$EUID" != 0 ]]; then
-        echo "mcrestore: Insufficient privilege. Exiting."
-        exit
+### KEY GUARD
+
+if [[ "$1" != "pleasedontdothis" ]]; then
+    echo "mcrestoreworld: Not intended to be run directly. Exit (13)."
+    exit 13
 fi
 
 
 
-# SCRIPT VARIABLES
+#### SCRIPT PARAMETERS ################
 
-SERVER=$1
-BACKUP_DIR=$(cat $HOMEDIR/gorp.conf | grep "^[^#;]" | grep 'BACKUPS=' | cut -d '=' -f 2)
-
+SERVER=$2
+BACKUP_DIR=$(getBackupDest)
 
 
 ####
@@ -33,20 +34,20 @@ BACKUP_DIR=$(cat $HOMEDIR/gorp.conf | grep "^[^#;]" | grep 'BACKUPS=' | cut -d '
 
 # PARAM GUARD
 
-if [ "$SERVER" = "" ]; then
-    echo "mcrestore: Please specify a server. Exiting."
-    exit
+if [[ "$SERVER" = "" ]]; then
+    echo "mcrestoreworld: Bad input. Expected: gorp restore-world [server-name]. Exit (14)."
+    exit 14
 fi
 
 
 
 # SERVER DIRECTORY GUARD
 
-if [ -d "$BACKUP_DIR/$SERVER" ]; then
+if [[ -d "$BACKUP_DIR/$SERVER" ]]; then
     sleep 0.005
 else
-    echo "mcrestore: Specified server has no backups to restore from. Exiting."
-    exit
+    echo "mcrestoreworld: Server has no backups to restore from. Exit (54)."
+    exit 54
 fi
 
 
@@ -54,12 +55,12 @@ fi
 # SCREEN GUARD
 
 if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
-        echo "mcrestore: Server '$SERVER' is running. Stop the server and then perform a restore. Exiting."
-        exit
+        echo "mcrestoreworld: Server cannot be running. Exit (34)."
+        exit 34
 fi
 
 
 
 # RUN RESTORE WORKER
 
-/usr/local/bin/gorpmc/worker/restoreworld.sh $SERVER
+/usr/local/bin/gorpmc/worker/restoreworld.sh pleasedontdothis $SERVER
diff --git a/action/mcstart b/action/mcstart
--- a/action/mcstart
+++ b/action/mcstart
@@ -11,18 +11,21 @@
 
 
 
-# PERMISSIONS GUARD
+#### GUARDS ################
 
-if [[ "$EUID" != 0 ]]; then
-        echo "mcstart: Insufficient privilege. Exiting."
-        exit
+### KEY GUARD
+
+if [[ "$1" != "pleasedontdothis" ]]; then
+    echo "mcstart: Not intended to be run directly. Exit (13)."
+    exit 13
 fi
 
 
 
-# SCRIPT VARIABLES
+#### SCRIPT PARAMETERS ################
 
-SERVER=$1
+SERVER=$2
+HOMEDIR=$(getHomedir)
 
 
 
@@ -32,20 +35,20 @@ SERVER=$1
 
 # PARAM GUARD
 
-if [ "$SERVER" = "" ]; then
-    echo "mcstart: Please specify a server. Exiting."
-    exit
+if [[ "$SERVER" = "" ]]; then
+    echo "mcstart: Bad input. Expected: gorp start [server-name]. Exit (14)."
+    exit 14
 fi
 
 
 
 # SERVER DIRECTORY GUARD
 
-if [ -d "$HOMEDIR/servers/$SERVER" ]; then
+if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
     cd $HOMEDIR/servers/$SERVER
 else
-    echo "mcstart: Specified server doesn't exist. Exiting."
-    exit
+    echo "mcstart: Server not found. Exit (30)."
+    exit 30
 fi
 
 
@@ -53,12 +56,12 @@ fi
 # SCREEN GUARD
 
 if [[ $(screen -ls | grep "$SERVER")  != "" ]]; then
-        echo "mcstart: Server '$SERVER' is already running. Exiting."
-        exit
+        echo "mcstart: Server already running. Exit (33)."
+        exit 33
 fi
 
 
 
 # RUN STARTUP WORKER
 
-/usr/local/bin/gorpmc/worker/start.sh $SERVER
+/usr/local/bin/gorpmc/worker/start.sh pleasedontdothis $SERVER
diff --git a/action/mcstop b/action/mcstop
--- a/action/mcstop
+++ b/action/mcstop
@@ -12,19 +12,22 @@
 
 
 
-# PERMISSION GUARD
+#### GUARDS ################
 
-if [[ "$EUID" != 0 ]]; then
-    echo "mcstop: Insufficient privilege. Exiting."
-    exit
+### KEY GUARD
+
+if [[ "$1" != "pleasedontdothis" ]]; then
+    echo "mcstop: Not intended to be run directly. Exit (13)."
+    exit 13
 fi
 
 
 
-# SCRIPT VARIABLES
+#### SCRIPT PARAMETERS ################
 
-SERVER=$1
-ARG=$2
+SERVER=$2
+ARG=$3
+HOMEDIR=$(getHomedir)
 
 
 
@@ -32,56 +35,50 @@ ARG=$2
 
 
 
-# PARAM GUARD
+# PARAM RT-GUARD
 
-if [ "$SERVER" = "" ]; then
-    echo "mcstop: Please specify a server"
-    exit
-
-elif [ "$SERVER" == 'fast' ] || [ "$SERVER" == 'now' ] || [ "$SERVER" == 'power' ]; then
-    echo "mcstop: Malformed command. Expected form: 'mcstop <server> <argument>'"
+if [ "$SERVER" = "" ] || [ "$SERVER" == 'fast' ] || [ "$SERVER" == 'now' ] || [ "$SERVER" == 'power' ]; then
+    echo "mcstop: Bad input. Expected: gorp stop [server-name] <option>. Exit (14)."
     exit
 fi
 
 
 
-# SERVER DIRECTORY GUARD
+# SERVER DIRECTORY RT-GUARD
 
-if [ -d "$HOMEDIR/servers/$SERVER" ]; then
+if [[ -d "$HOMEDIR/servers/$SERVER" ]]; then
     cd $HOMEDIR/servers/$SERVER
 else
-    echo "mcstop: Specified server doesn't exist. Exiting."
-    exit
+    echo "mcstop: Server not found. Exit (30)."
+    exit 30
 fi
 
 
 
-# NO SCREEN GUARD
+# NO SCREEN RT-GUARD
 if [[ $(screen -ls | grep "$SERVER")  = "" ]]; then
-        echo "mcstop: Server '$SERVER' is not running. Exiting."
-        exit
+        echo "mcstop: Server not running. Exit (32)."
+        exit 32
 fi
 
 
 
 # RUN WORKERS BASED ON PASSED PARAMS
 
-if [ -z "$ARG" ]; then
-    /usr/local/bin/gorpmc/worker/backupworld.sh $SERVER
-    /usr/local/bin/gorpmc/worker/warning.sh $SERVER stop
-    /usr/local/bin/gorpmc/worker/shutdown.sh $SERVER
+if [[ -z "$ARG" ]]; then
+    /usr/local/bin/gorpmc/worker/backupworld.sh pleasedontdothis $SERVER
+    /usr/local/bin/gorpmc/worker/warning.sh pleasedontdothis $SERVER stop
+    /usr/local/bin/gorpmc/worker/shutdown.sh pleasedontdothis $SERVER
 
-elif [ $ARG == "power" ]; then
-    /usr/local/bin/gorpmc/worker/warning.sh $SERVER power
-    /usr/local/bin/gorpmc/worker/shutdown.sh $SERVER
+elif [[ $ARG == "power" ]]; then
+    /usr/local/bin/gorpmc/worker/warning.sh pleasedontdothis $SERVER power
+    /usr/local/bin/gorpmc/worker/shutdown.sh pleasedontdothis $SERVER
 
-elif [ $ARG == "fast" ]; then
-    /usr/local/bin/gorpmc/worker/warning.sh $SERVER stop
-    /usr/local/bin/gorpmc/worker/shutdown.sh $SERVER
+elif [[ $ARG == "fast" ]]; then
+    /usr/local/bin/gorpmc/worker/warning.sh pleasedontdothis $SERVER stop
+    /usr/local/bin/gorpmc/worker/shutdown.sh pleasedontdothis $SERVER
 
-elif [ $ARG == "now" ]; then
-    /usr/local/bin/gorpmc/worker/shutdown.sh $SERVER
+elif [[ $ARG == "now" ]]; then
+    /usr/local/bin/gorpmc/worker/shutdown.sh pleasedontdothis $SERVER
 
-else
-    echo "mcstop: Invalid second parameter. Exiting."
 fi
