major updates to gorp - 1.4.0

diff --git a/gorp b/gorp
--- a/gorp
+++ b/gorp
@@ -32,24 +32,90 @@ fi
 
 source /usr/local/bin/gorpmc/worker/i_getconfigparams.sh
 
-if [[ "$1" == "-q" ]]; then
-    TESTSTRING=pleaseshutup
-    ACTION=$2
-    ARG1=$3
-    ARG2=$4
 
-elif [[ "$1" == "-Q" ]]; then
-    TESTSTRING=pleasebesilent
-    ACTION=$2
-    ARG1=$3
-    ARG2=$4
 
-else
-    TESTSTRING=pleasedontdothis
-    ACTION=$1
-    ARG1=$2
-    ARG2=$3
-fi
+### SET DEFAULT PARAMS FOR NO FLAGS
+
+TESTSTRING=pleasedontdothis
+ACTION=$1
+ARG1=$2
+ARG2=$3
+OUTPUT=true
+ERRORS=true
+
+
+
+### CHECK FOR FLAGS AND ADJUST PARAMS
+
+OPTIND=1
+while getopts ":fg:hnqQs:t:u:vy" flag; do
+    case $flag in
+        # GLOBAL FLAGS
+        h)  # help (gorp -h)
+            ACTION="help"
+            ;;
+        q)  # quiet (gorp -q [command])
+            TESTSTRING=pleaseshutup
+            ACTION=$2
+            ARG1=$3
+            ARG2=$4
+            OUTPUT=false
+            ERRORS=true
+            ;;
+        Q)  # Quiet (gorp -Q [command])
+            TESTSTRING=pleasebesilent
+            ACTION=$2
+            ARG1=$3
+            ARG2=$4
+            OUTPUT=false
+            ERRORS=false        
+            ;;
+        s)  # status (gorp -s [server])
+            ACTION="status"
+            ARG1="$OPTARG"
+            ;;
+        t)  #tail (gorp -t [server])
+            ACTION="tail"
+            ARG1="$OPTARG"
+            ;;
+        v)  # version (gorp -v)
+            ACTION="version"
+            ;;
+        
+        # RUNTIME FLAGS
+        f)  # fast (gorp -f stop|restart [server])
+            ACTION=$2
+            ARG1=$3
+            ARG2="-f"
+            ;;
+        g)  # gamever (gorp -g [version] get-jar)
+            ACTION="get-jar"
+            ARG1="-g"
+            ARG2="$OPTARG"
+            ;;
+        n)  # now (gorp -n stop|restart [server])
+            ACTION=$2
+            ARG1=$3
+            ARG2="-n"
+            ;;
+        u)  # url (gorp -u [url] get-jar)
+            ACTION="get-jar"
+            ARG1="-u"
+            ARG2="$OPTARG"
+            ;;
+        y)
+            ACTION=$2
+            ARG1=$3
+            ARG2="-y"
+            ;;
+        
+        # UNKNOWN FLAGS (all other entries)
+        *)
+            echo "gorp: Invalid or unknown flags. Exit."
+            exit 1
+            ;;
+    esac
+done
 
 
 
@@ -68,7 +134,7 @@ fi
 ### PARAMS RT-GUARD
 
 if [[ "$GAMEVER" == "" ]] || [[ "$RAM" == "" ]] || [[ "$HOMEDIR" == "" ]] || [[ "$BACKUP_DEST" == "" ]] || [[ "$ARCHIVE_DEST" == "" ]] || [[ "$LATEST_JAR" == "" ]]; then
-    echo "gorp: One or more required options in gorp.conf not set. Exit (15)."
+    if $ERRORS; then echo "gorp: One or more required options in gorp.conf not set. Exit (15)."; fi
     exit 15
 fi
 
@@ -123,7 +189,7 @@ elif [[ "$ACTION" == "power" ]]; then
     /usr/local/bin/gorpmc/action/mcpower $TESTSTRING
 
 elif [[ "$ACTION" == "start" ]]; then
-    /usr/local/bin/gorpmc/action/mcstart $TESTSTRING $ARG1
+    /usr/local/bin/gorpmc/action/mcstart $TESTSTRING $ARG1 $ARG2
 
 elif [[ "$ACTION" == "stop" ]]; then
     /usr/local/bin/gorpmc/action/mcstop $TESTSTRING $ARG1 $ARG2
@@ -137,16 +203,16 @@ elif [[ "$ACTION" == "help" ]]; then
 elif [[ "$ACTION" == "upgrade" ]]; then
     /usr/local/bin/gorpmc/action/gorpupgrade $TESTSTRING
 
-elif [[ "$ACTION" == "-v" ]]; then
+elif [[ "$ACTION" == "version" ]]; then
     /usr/local/bin/gorpmc/action/gorpversion
 
-elif [[ "$ACTION" == "-s" ]]; then
+elif [[ "$ACTION" == "status" ]]; then
     /usr/local/bin/gorpmc/action/mcserverstatus $TESTSTRING $ARG1
 
-elif [[ "$ACTION" == "-f" ]]; then
+elif [[ "$ACTION" == "tail" ]]; then
     tail -f $HOMEDIR/servers/$ARG1/logs/latest.log
 
-elif [[ "$ACTION" == "list-servers" ]]; then
+elif [[ "$ACTION" == "ls" ]]; then
     echo $(ls $HOMEDIR/servers)
 
 elif [[ "$ACTION" == "move-home" ]]; then
